schema_version = "1.0.0"

id = "meshstats"
version = "1.3.2"
name = "Meshstats"
tagline = "Mesh statistics"
maintainer = "Atamert Ölçgen <muhuk@muhuk.com>"
type = "add-on"
website = "https://github.com/muhuk/meshstats"

tags = ["Mesh", "Modeling"]

blender_version_min = "4.2.2"
# blender_version_max = "5.1.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

# [build]
# paths_exclude_pattern = [
#   "__pycache__/",
#   "/.git/",
#   "/*.zip",
# ]